<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RewardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Rewards are typically generated by the application logic
        // (i.e., the ExchangeInitiator::confirmReceipt method) and not seeded.
        // This file exists for structure.
    }
}